# Generated by Django 5.2.5 on 2025-08-22 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_alter_inventoryitem_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
    ]
