# Generated by Django 5.2.5 on 2025-08-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_price'),
        ('inventory', '0006_alter_supplier_email_alter_supplier_phone'),
    ]

    operations = [
    ]
